spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    data: classpath:data.sql
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/prices
    username: skillovila
    password: random123
    initialization-mode: always
conversion-rates:
  usd: 72.45
  euro: 99.91